name: Docker Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: read
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build with Docker Compose
        run: docker compose build

      - name: Create artifact directory
        run: mkdir -p artifacts

      - name: Create test file
        run: echo "Test content" > artifacts/test.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: artifacts/
          retention-days: 1 