name: Docker Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Debug Info
      run: |
        echo "GitHub Workspace: $GITHUB_WORKSPACE"
        echo "GitHub SHA: $GITHUB_SHA"
        ls -la
        docker --version
        docker compose version

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and test services
      run: |
        echo "Starting docker compose build..."
        docker compose build --no-cache
        echo "Starting services..."
        docker compose up -d
        echo "Waiting for services to start..."
        sleep 30
        echo "Checking service status..."
        docker compose ps
        echo "Testing health endpoint..."
        curl -v http://localhost:3000/health || exit 1
        echo "Stopping services..."
        docker compose down

    - name: List Docker images
      run: |
        echo "Available Docker images:"
        docker images
        mkdir -p docker-images

    - name: Save Docker images
      run: |
        echo "Saving Docker images..."
        services=("api-gateway" "menu-service" "order-service" "payment-service" "inventory-service" "customer-service")
        for service in "${services[@]}"; do
          echo "Saving $service image..."
          docker save "$service:latest" -o "docker-images/$service.tar" || echo "Failed to save $service"
        done
        ls -la docker-images/

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: docker-images
        path: docker-images/
        retention-days: 1 