name: Docker Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build API Gateway
      uses: docker/build-push-action@v4
      with:
        context: ./api-gateway
        push: false
        tags: api-gateway:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build Menu Service
      uses: docker/build-push-action@v4
      with:
        context: ./menu-services
        push: false
        tags: menu-service:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build Order Service
      uses: docker/build-push-action@v4
      with:
        context: ./order-services
        push: false
        tags: order-service:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build Payment Service
      uses: docker/build-push-action@v4
      with:
        context: ./payment-services
        push: false
        tags: payment-service:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build Inventory Service
      uses: docker/build-push-action@v4
      with:
        context: ./inventory-services
        push: false
        tags: inventory-service:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build Customer Service
      uses: docker/build-push-action@v4
      with:
        context: ./customer-services
        push: false
        tags: customer-service:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test Docker Compose
      run: |
        docker compose build
        docker compose up -d
        sleep 30
        docker compose ps
        curl -f http://localhost:3000/health || exit 1
        docker compose down

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: docker-images
        path: |
          api-gateway
          menu-services
          order-services
          payment-services
          inventory-services
          customer-services 