name: Docker Publish

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Convert owner to lowercase
        run: |
          echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/cafe-management

      - name: Build and push API Gateway
        uses: docker/build-push-action@v4
        with:
          context: ./api-gateway
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/api-gateway:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Menu Service
        uses: docker/build-push-action@v4
        with:
          context: ./menu-services
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/menu-service:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Order Service
        uses: docker/build-push-action@v4
        with:
          context: ./order-services
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/order-service:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Payment Service
        uses: docker/build-push-action@v4
        with:
          context: ./payment-services
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/payment-service:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Inventory Service
        uses: docker/build-push-action@v4
        with:
          context: ./inventory-services
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/inventory-service:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Customer Service
        uses: docker/build-push-action@v4
        with:
          context: ./customer-services
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/customer-service:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Check images
        if: github.event_name != 'pull_request'
        run: |
          docker images | grep ${{ env.REGISTRY }}/${{ env.OWNER_LC }} 