name: Docker Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and test services
      run: |
        docker compose build
        docker compose up -d
        sleep 30
        docker compose ps
        curl -f http://localhost:3000/health || exit 1
        docker compose down

    - name: Save Docker Images
      run: |
        mkdir -p docker-images
        docker save api-gateway:latest -o docker-images/api-gateway.tar
        docker save menu-service:latest -o docker-images/menu-service.tar
        docker save order-service:latest -o docker-images/order-service.tar
        docker save payment-service:latest -o docker-images/payment-service.tar
        docker save inventory-service:latest -o docker-images/inventory-service.tar
        docker save customer-service:latest -o docker-images/customer-service.tar

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: docker-images
        path: docker-images/*.tar 