name: Cafe Management System Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository_owner }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Download previous artifacts if they exist
      - name: Download previous artifacts
        continue-on-error: true
        uses: actions/download-artifact@v3
        with:
          name: workflow-logs
          path: previous-logs

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl zip unzip
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

      - name: Convert repository owner to lowercase
        run: |
          echo "OWNER_LC=${IMAGE_PREFIX,,}" >> $GITHUB_ENV
          echo "Using lowercase owner: ${{ env.OWNER_LC }}"

      # Build each service with proper error handling
      - name: Build Services
        run: |
          # Function to build a service
          build_service() {
            local service=$1
            local path=$2
            echo "Building $service from $path..."
            if [ ! -d "$path" ]; then
              echo "Directory $path does not exist!"
              exit 1
            fi
            docker build -t ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/$service:latest $path || {
              echo "Failed to build $service"
              exit 1
            }
          }

          # Build all services
          build_service "api-gateway" "./api-gateway"
          build_service "menu-service" "./menu-services"
          build_service "order-service" "./order-services"
          build_service "payment-service" "./payment-services"
          build_service "inventory-service" "./inventory-services"
          build_service "customer-service" "./customer-services"

      - name: List built images
        run: |
          echo "Listing all built Docker images:"
          docker images | grep "${{ env.REGISTRY }}/${{ env.OWNER_LC }}" || true

      # Start services and test with proper error handling
      - name: Start and test services
        run: |
          echo "Starting services..."
          docker compose up -d || {
            echo "Failed to start services"
            docker compose logs
            exit 1
          }
          
          echo "Waiting for services to start..."
          sleep 45  # Increased wait time

          # Function to test a service
          test_service() {
            local service=$1
            local port=$2
            echo "Testing $service on port $port..."
            for i in {1..3}; do
              if curl -f http://localhost:$port/health; then
                echo "$service is healthy"
                return 0
              fi
              echo "Attempt $i failed, retrying in 10s..."
              sleep 10
            done
            echo "Failed to test $service after 3 attempts"
            return 1
          }

          # Test all services
          test_service "API Gateway" "3000"
          test_service "Menu Service" "3001"
          test_service "Order Service" "3002"
          test_service "Payment Service" "3003"
          test_service "Inventory Service" "3004"
          test_service "Customer Service" "3005"

      # Push images if on main branch
      - name: Push images
        if: github.ref == 'refs/heads/main'
        run: |
          # Function to push a service
          push_service() {
            local service=$1
            echo "Pushing $service..."
            docker push ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/$service:latest || {
              echo "Failed to push $service"
              exit 1
            }
          }

          # Push all services
          push_service "api-gateway"
          push_service "menu-service"
          push_service "order-service"
          push_service "payment-service"
          push_service "inventory-service"
          push_service "customer-service"

      # Modified artifact collection and upload
      - name: Prepare artifacts
        if: always()
        run: |
          # Create artifact directories
          mkdir -p artifacts/logs
          mkdir -p artifacts/docker
          mkdir -p artifacts/system
          
          # Save Docker logs
          echo "=== Docker Compose Logs ===" > artifacts/logs/docker.log
          docker compose logs --no-color > artifacts/logs/docker.log 2>&1
          
          # Save Docker images info
          echo "=== Docker Images ===" > artifacts/docker/images.log
          docker images > artifacts/docker/images.log 2>&1
          
          # Save system info
          echo "=== System Info ===" > artifacts/system/system.log
          uname -a > artifacts/system/system.log 2>&1
          df -h >> artifacts/system/system.log 2>&1
          
          # Save service status
          echo "=== Service Status ===" > artifacts/docker/status.log
          docker compose ps > artifacts/docker/status.log 2>&1

          # Create metadata file
          cat << EOF > artifacts/metadata.json
          {
            "run_id": "${{ github.run_id }}",
            "run_number": "${{ github.run_number }}",
            "workflow": "${{ github.workflow }}",
            "repository": "${{ github.repository }}",
            "branch": "${{ github.ref }}",
            "commit": "${{ github.sha }}"
          }
          EOF

          # Create artifact manifest
          find artifacts -type f -exec sha256sum {} \; > artifacts/manifest.txt

      # Primary artifact upload with explicit configuration
      - name: Upload workflow artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: workflow-logs
          path: |
            artifacts/**/*.log
            artifacts/**/*.json
            artifacts/manifest.txt
          if-no-files-found: error
          retention-days: 5

      # Verify artifact upload
      - name: Verify artifact upload
        if: always()
        run: |
          echo "Verifying artifact upload..."
          # List uploaded files
          find artifacts -type f -exec ls -l {} \;
          
          # Check manifest
          echo "Checking manifest..."
          cat artifacts/manifest.txt
          
          # Verify metadata
          echo "Checking metadata..."
          cat artifacts/metadata.json

      # Download artifacts to verify
      - name: Download and verify artifacts
        if: always()
        uses: actions/download-artifact@v3
        with:
          name: workflow-logs
          path: download-verify

      - name: Verify downloaded artifacts
        if: always()
        run: |
          echo "Verifying downloaded artifacts..."
          if [ -d "download-verify" ]; then
            find download-verify -type f -exec ls -l {} \;
            echo "Download verification successful"
          else
            echo "Error: Download verification failed"
            exit 1
          fi

      # Clean up
      - name: Cleanup
        if: always()
        run: |
          echo "Cleaning up..."
          docker compose down
          docker system prune -f
          rm -rf artifacts download-verify 